<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headScript(); ?>
  </head>

<body>
  
<div class="navbar navbar-fixed-top">
  
  <div class="navbar-inner">
    
    <div class="container">
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>        
      </a>
      
      <a class="brand" href="<?php echo $this->baseUrl('/login'); ?>">Fortuna CMS</a>
      
      <div class="nav-collapse">

        <?php echo $this->navigation()->menu()->render(); ?>
      
        <ul class="nav pull-right">
          <li>
            <a href="<?php echo $this->baseUrl('/'); ?>"><i class="icon-chevron-left"></i> <?php echo $this->translate('Homepage'); ?></a>
          </li>
        </ul>
        
      </div> <!-- /nav-collapse -->
      
    </div> <!-- /container -->
    
  </div> <!-- /navbar-inner -->
  
</div> <!-- /navbar -->


<div id="login-container">
  
  
  <div id="login-header">
    
    <h3><?php echo $this->translate($this->pageTitle); ?></h3>
    
  </div> <!-- /login-header -->
  
  <div id="login-content" class="clearfix">
    <?php if (isset($this->messages)): ?>
      <?php foreach ($this->messages as $message): ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">×</a>
          <?php echo $this->translate($message); ?>
        </div>
      <?php endforeach; ?>
      <script type="text/javascript">
        $(document).ready(function() {
          $('#login-content').effect('shake', { times: 1 }, 100);
        });
      </script>

    <?php endif; ?>
    
    <?php echo $this->layout()->content; ?>
  </div> <!-- /login-content -->
  
  
</div> <!-- /login-wrapper -->

  </body>
</html>
