<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headScript(); ?>
  </head>

<body>
  
<div class="navbar navbar-fixed-top">
  
  <div class="navbar-inner">
    
    <div class="container">
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>        
      </a>
      
      <a class="brand" href="<?php echo $this->baseUrl('/admin/login/'); ?>">Fortuna CMS</a>
      
      <div class="nav-collapse">

        <?php echo $this->navigation()->menu()->render(); ?>
      
        <ul class="nav pull-right">

          <li>
            <a href="<?php echo $this->baseUrl('/'); ?>"><i class="icon-chevron-left"></i> <?php echo $this->translate('Homepage'); ?></a>
          </li>

          <li>
            <a href="<?php echo $this->baseUrl('/admin'); ?>"><i class="icon-chevron-left"></i> <?php echo $this->translate('Admin'); ?></a>
          </li>
         
        </ul>
        
      </div> <!-- /nav-collapse -->
      
    </div> <!-- /container -->
    
  </div> <!-- /navbar-inner -->
  
</div> <!-- /navbar -->




<div id="content">
  
  <div class="container">

    <h1 class="page-title">
      <?php echo $this->placeholder('pageTitle'); ?>
    </h1>

    <?php echo $this->layout()->content; ?>

    <script type="text/javascript">
        $(document).ready(function() {
            $('select').chosen();
        });
    </script>
      
      
    </div> <!-- /row -->
    
  </div> <!-- /container -->
  
</div> <!-- /content -->
          
  
<div id="footer">
  
  <div class="container">       
    <hr>
    <p>Fortuna CMS <?php echo $this->version; ?> | PHP <?php echo phpversion(); ?></p>
  </div> <!-- /container -->
  
</div> <!-- /footer -->

  </body>
</html>