<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headScript(); ?>

	<style type="text/css">
	  @media (min-width: 980px) {
		body {
		  padding-top: 60px;
		  padding-bottom: 40px;
		}
	  }
	</style>
  </head>

  <body>

   <div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
		<div class="container-fluid">
		  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </a>
		  <a class="brand" href="<?php echo $this->baseUrl(); ?>"><?php echo $this->placeholder('appTitle'); ?></a>
		  <div class="nav-collapse">
			<?php echo $this->navigation()->menu()->render(); ?>

			<? if (isset($this->identity)): ?>
			<ul class="nav pull-right">
			  <?php if (isset($this->article)): ?>
				<li>
					<a href="<?php echo $this->baseUrl('admin/show-article/id/' . $this->article['id']); ?>">
					<i class="icon-pencil"></i> <?php echo $this->translate('Edit'); ?> <strong><?php echo $this->article['title']; ?></strong>
					</a>
				</li>
			  <?php elseif (isset($this->category)): ?>
			  	<li>
					<a href="<?php echo $this->baseUrl('admin/show-category/id/' . $this->category['id']); ?>">
					<i class="icon-tag"></i> <?php echo $this->translate('Edit'); ?> <strong><?php echo $this->category['name']; ?></strong>
					</a>
				</li>
			  <?php endif; ?>

			  <li>
				<a href="<?php echo $this->baseUrl('/admin'); ?>"><i class="icon-chevron-left"></i> <?php echo $this->translate('Admin'); ?></a>
			  </li>
			  
			  <li class="divider-vertical"></li>
			  
			  <li class="dropdown">
				
				<a data-toggle="dropdown" class="dropdown-toggle " href="#">
				  <?php echo $this->identity->firstname; ?> <?php echo $this->identity->lastname; ?> <b class="caret"></b>              
				</a>
				
				<ul class="dropdown-menu">
				  <li>
					<a href="<?php echo $this->baseUrl('admin/account/'); ?>"><i class="icon-user"></i> <?php echo $this->translate('Account Settings'); ?></a>
				  </li>
				  
				  <li class="divider"></li>
				  
				  <li>
					<a href="<?php echo $this->baseUrl('auth/logout/'); ?>"><i class="icon-off"></i> <?php echo $this->translate('Logout'); ?></a>
				  </li>
				</ul>
			  </li>
			</ul>
		  <?php endif; ?>
		  </div><!--/.nav-collapse -->
		</div>
	  </div>
	</div>

	<div class="container-fluid">

		  <h1 class="page-header">
			<?php echo $this->placeholder('pageTitle'); ?>
		  </h1>

		  <?php echo $this->layout()->content; ?>

	  <hr>

	  <footer>
		<p>&copy; <?php echo $this->placeholder('appTitle'); ?> <?php echo date('Y'); ?></p>
	  </footer>

	</div><!--/.fluid-container-->

  </body>
</html>