<?php if ($this->schema['update']): ?>
	 <div class="alert alert-info">
      <a class="close" data-dismiss="alert">×</a>
      <?php echo $this->translate('There is an schema available to migrate. Please click the button to do so.'); ?>
    </div>
<?php endif; ?>
<div class="row">      
    <div class="span7">

    	<div class="widget">
			<div class="widget-header">
				<i class="icon-cog"></i>
				<h3><?php echo $this->translate('Settings'); ?></h3>
			</div> <!-- /widget-header -->
		             
			<div class="widget-content">
				<?php echo $this->form; ?>
			</div>
		</div>
		
    </div> <!-- /span9 -->
    <div class="span5">
    	<div class="widget widget-table">
			<div class="widget-header">
				<i class="icon-list-alt"></i>
				<h3><?php echo $this->translate('Database Schema'); ?></h3>
			</div> <!-- /widget-header -->     
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tbody>
						<tr>
							<td><?php echo $this->translate('Latest'); ?></td>
							<td><?php echo $this->schema['latest']; ?></td>
						</tr>
						<tr>
							<td><?php echo $this->translate('Installed'); ?></td>
							<td><?php echo $this->schema['installed'] ? $this->schema['installed'] : '-'; ?></td>
						</tr>
					</tbody>
						<?php if ($this->schema['update']): ?>
						<tfoot>
							<tr>
								<td colspan="2">
									<a data-toggle="modal" href="#migrate" class="btn btn-large center"><?php echo $this->translate('Migrate Schema'); ?> <strong><?php echo $this->schema['latest']; ?></strong></a>
									<div id="migrate" class="modal hide fade">
							            <div class="modal-header">
							              <a class="close" data-dismiss="modal">×</a>
							              <strong><?php echo $this->translate('Migrate Database Schema'); ?></strong>
							            </div>
							            <div class="modal-body">
							              <p><?php echo $this->translate('Migrate the schema <strong>%s</strong>?', $this->schema['latest']); ?></p>
							            </div>
							            <div class="modal-footer">
							              <a href="#" class="btn" data-dismiss="modal"><?php echo $this->translate('Cancel'); ?></a>
							              <a href="<?php echo $this->baseUrl('install/migrate/'); ?>" class="btn btn-primary"><?php echo $this->translate('Migrate'); ?></a>
							            </div>
							          </div>
									</div>
								</td>
							</tr>
						<tfoot>
						<?php endif; ?>
				</table>
			</div>
		</div>

    	<div class="widget widget-table">
			<div class="widget-header">
				<i class="icon-road"></i>
				<h3><?php echo $this->translate('Server Requirements'); ?></h3>
			</div> <!-- /widget-header -->
		             
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tbody>
						<tr>
							<td>PHP <?php echo $this->php['needed']; ?></td>
							<td><i class="icon-<?php echo $this->php['found'] ? 'ok' : 'remove'; ?>"></i></td>
						</tr>
						<?php foreach ($this->extensions as $extension => $found): ?>
						<tr>
							<td><?php echo $extension; ?></td>
							<td><i class="icon-<?php echo $found ? 'ok' : 'remove'; ?>"></i>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
    	<div class="widget widget-table">
			<div class="widget-header">
				<i class="icon-file"></i>
				<h3><?php echo $this->translate('Writable Paths'); ?></h3>
			</div> <!-- /widget-header -->
		             
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tbody>
						<?php foreach ($this->writable as $path => $writable): ?>
						<tr>
							<td><?php echo $path; ?></td>
							<td><i class="icon-<?php echo $writable ? 'ok' : 'remove'; ?>"></i>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
    </div>
</div>