<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headScript(); ?>
  </head>

<body>
  
<div class="navbar navbar-fixed-top">
  
  <div class="navbar-inner">
    
    <div class="container">
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>        
      </a>
      
      <a class="brand" href="<?php echo $this->baseUrl('/admin/login/'); ?>">Fortuna CMS</a>
      
    </div> <!-- /container -->
    
  </div> <!-- /navbar-inner -->
  
</div> <!-- /navbar -->


    <div class="container">
      
      <div class="row">
        
        <div class="span12">
          
          <div class="error-container">
            <h1>Oops!</h1>
            
            <h2><?php echo $this->title; ?></h2>
            
            <div class="error-details">
            <code><?php echo $this->message; ?></code>

            </div> <!-- /error-details -->

            <div class="error-actions">
              <a href="javascript:history.back()" class="btn btn-large">
                <i class="icon-chevron-left"></i>
                &nbsp;
                <?php echo $this->translate('Go Back'); ?>        
              </a>
              
            </div> <!-- /error-actions -->
                  
          </div> <!-- /error-container -->      
          
        </div> <!-- /span12 -->
        
      </div> <!-- /row -->
      
    </div> <!-- /container -->

  </body>
</html>
